services:
  api:
    image: ${DOCKER_IMAGE}
    ports:
      - ${DOCKER_PORT}:3000
    environment:
      - NODE_ENV=${NODE_ENV}

      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - API_URL=${API_URL}
